---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./drone.yaml
  - ./emberstack.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./kubernetes-sigs-descheduler.yaml
  - ./kubernetes-sigs-external-dns.yaml
  - ./kubernetes-sigs-metrics-server.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./renovate.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./vector.yaml
